# Generated by Django 4.0.6 on 2022-07-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_order_id_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='details',
            new_name='products',
        ),
    ]
