# Generated by Django 4.0.6 on 2022-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_details_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(related_name='detail', through='api.OrderDetail', to='api.product'),
        ),
    ]
