# Generated by Django 4.0.6 on 2022-07-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_products_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(through='api.OrderDetail', to='api.product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('product', 'order')},
        ),
    ]
