# Generated by Django 4.0.6 on 2022-07-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='movement_type',
            field=models.CharField(choices=[('INGRESS', 'INGRESS'), ('EGRESS', 'EGRESS')], db_index=True, default='EGRESS', max_length=10),
        ),
    ]
